### ISSUE TITLE
Service Discovery for K8s

### ISSUE THREAD

**Issue by dushaniw** [wso2/apk#1]

**Comment by VajiraPrabuddhaka** [comment]
As per the requirement Runtime API should be capable of listing services available in the k8s cluster that the Runtime API is running and make them available for the Runtime API via exposing an endpoint.

As per the OAS defined in https://github.com/wso2/apk/issues/42 it has following endpoints for service discovery related operations.

- /services - List/search services
- /services/{serviceId} - Get details of a particular service
- /services/{serviceId}/usage - Get usage details for a particular service

We did the initial implementation for above using the [client-go](https://github.com/kubernetes/client-go) library by directly calling k8s API server and accessing services across namespaces.

**Comment by VajiraPrabuddhaka** [comment]
Closing this issue as this is tracked in https://github.com/wso2/apk/issues/78
