### ISSUE TITLE
Ratelimit issues

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1008]
**Description:**
- when route doesn't have a method specified, all methods separately applies the ratelimit policy -> this should be apply one ratelimit for resource without considering the operation

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Tharsanan1** [comment]
I tested this. When invoking the same route with different HTTP methods(when the user has not specified the method to the CR) same rate-limit counter is used, which is the expected behavior. Hence closing this issue.
