### ISSUE TITLE
Can not invoke APIs create through importing API definition

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/apk#1021]
## Description
While testing `POST /apis/import-definition` resource in `runtime-api.yaml` it was identified that the created API can not be invoked. 
It was observed that in the `Authentication` CR name of the `HTTPRoute` is not the same as in `API`.

API CR:
```
Production:
    Http Route Refs:
      01edd8ea-1be0-1886-9b99-e1e4dafeefb6
  Sandbox:
    Http Route Refs:
      01edd8ea-1be0-1886-9d22-56f9a26f76b4
```

Authentication CR:
```
Spec:
  Override:
    Ext:
      Disabled:  true
    Type:        ext
  Target Ref:
    Group:      
    Kind:       Resource
    Name:       01edd8ea-1be0-1886-a132-da476802bc47
    Namespace:  apk
```

**Comment by RakhithaRR** [comment]
Observing similar error for migrated APIs as well since the migration client uses `import-definition` resource.

**Comment by CrowleyRajapakse** [comment]
Fixed <img width="1324" alt="Screenshot 2023-04-17 at 12 03 21" src="https://user-images.githubusercontent.com/23296184/232403210-50494622-7511-4608-a4e9-39b6948c3321.png">
