### ISSUE TITLE
APK Management server and Adapter implementation

### ISSUE THREAD

**Issue by dushaniw** [wso2/apk#11]
### Functionality of APK Agent Client
APK Agent is the responsible party for managing the data-plane cluster by managing its components as well as keeping the control plane sync-up with data-plane.

Mainly it has the following functionality

- Talks to the K8s API server and manages (Create, Update, Delete) resources in the K8s cluster(DP) -> Create APIs (in UI driven approach), Applying policies (from UI)
- Update rate limit service with rate limit policies -> Will be an xDS communication
- Update enforcer with subscription details, etc. -> Will be an xDS communication
- Should have a K8s operator to listen on the resources created on the DP cluster.
- Communicate with CP - xDS

### Functionality of APK Management Server
Management server is the responsible party for keeping the CP & DP sync by communicating with APK clients in each data-planes (or in the same control-plane when we run in a single cluster).

- Send API create/delete/update, Subscription, Policy events to the APK client - xDS
- Service registering.
- Update control plane with the resources created on dataplane(using cli) such as APIs, Policies, etc..

### APK Management Server to APK Agent Client Communication
API Agent Client should be associated with a k8s operator, which is watching for resource updates and sending the updates to the control plane’s Management Server and the Gateway.

Since we have only one control plane available, we decided to make this communication as a gRPC client to server streaming communication.

**Comment by npamudika** [comment]
Design and User Flows Document - https://docs.google.com/document/d/1F15zHzHi8ercomq5J3yR8P6TjkVWhhUQ1lnOF4_JCcU/edit?usp=sharing

Events and Data Document - https://docs.google.com/document/d/1opdltBxJIkz3Tn_CsxXbHI7RrhmsXaSgZAq27oayr_s/edit?usp=sharing

DP and CP K8s CRDs for APK - https://docs.google.com/document/d/1CL5ug6neMn-caLbjzLOJms8TNuMSw9evSaEHjQRFudQ/edit?usp=sharing

APK Management Server and Agent Client Implementation - https://docs.google.com/document/d/16-dsKnp_PgnAHdxoaTUTsP51yZ_unRTmf6dScGw9UgM/edit?usp=sharing

**Comment by npamudika** [comment]
## Sub Tasks
### Initial Designs and Definitions
- [ ] https://github.com/wso2/apk/issues/22
- [ ] https://github.com/wso2/apk/issues/23
- [ ] https://github.com/wso2/apk/issues/24

### Individualize Communication Protocols
- [ ] https://github.com/wso2/apk/issues/25
- [ ] https://github.com/wso2/apk/issues/26
- [ ] https://github.com/wso2/apk/issues/27
- [ ] https://github.com/wso2/apk/issues/28

### Handling CRDs
- [ ] https://github.com/wso2/apk/issues/29

### Agent Implementation
- [ ] https://github.com/wso2/apk/issues/30
- [ ] https://github.com/wso2/apk/issues/31
- [ ] https://github.com/wso2/apk/issues/32

### Management Server to DB Transactions
- [ ] https://github.com/wso2/apk/issues/33

**Comment by AmaliMatharaarachchi** [comment]
Restructuring the above task list below; 

## Initial Designs and Definitions
- [ ] https://github.com/wso2/apk/issues/22
- [ ] https://github.com/wso2/apk/issues/23
- [ ] https://github.com/wso2/apk/issues/24

## Management server XDS communication
- [ ] https://github.com/wso2/apk/issues/25
- [ ] https://github.com/wso2/apk/issues/26

## Adapter to Management Server gRPC unary communication
- [ ] https://github.com/wso2/apk/issues/27
- [ ] https://github.com/wso2/apk/issues/28

## Data partitioning for Choreo
- [ ] https://github.com/wso2/apk/issues/29

## Agent implementation - DP
- [ ] https://github.com/wso2/apk/issues/21

## Agent implementation - CP 
- [ ] https://github.com/wso2/apk/issues/19
- [ ] https://github.com/wso2/apk/issues/30
- [ ] https://github.com/wso2/apk/issues/31
- [ ] https://github.com/wso2/apk/issues/32

## Management Server to DB Communication
- [ ] https://github.com/wso2/apk/issues/33

**Comment by Amila-Rukshan** [comment]
Restructuring the above task list below; 

## Initial Designs and Definitions
- [x] https://github.com/wso2/apk/issues/22
- [x] https://github.com/wso2/apk/issues/23
- [x] https://github.com/wso2/apk/issues/24

## Management server XDS communication
- [x] https://github.com/wso2/apk/issues/25
- [ ] https://github.com/wso2/apk/issues/26

## Adapter to Management Server gRPC unary communication
- [ ] https://github.com/wso2/apk/issues/27
- [ ] https://github.com/wso2/apk/issues/28

## Data partitioning for Choreo
- [ ] https://github.com/wso2/apk/issues/29

## Agent implementation - DP
- [ ] https://github.com/wso2/apk/issues/21

## Agent implementation - CP 
- [ ] https://github.com/wso2/apk/issues/19
- [ ] https://github.com/wso2/apk/issues/30
- [ ] https://github.com/wso2/apk/issues/31
- [ ] https://github.com/wso2/apk/issues/32
- [ ] https://github.com/wso2/apk/issues/96

## Management Server to DB Communication
- [ ] https://github.com/wso2/apk/issues/33

**Comment by AmaliMatharaarachchi** [comment]
# Updated Task list

## GRPC Unary call for sending API updates to Management Server
- [ ] server](https://github.com/wso2/apk/issues/200)

**Comment by AmaliMatharaarachchi** [comment]
closing as this issue is no longer required.
