### ISSUE TITLE
[Enforcer] Validate Choreo and ELK analytics in enforcer

### ISSUE THREAD

**Issue by Amila-Rukshan** [wso2/apk#1127]
**Description:**
This is to validate and fix anything needed to get the choreo analytics and elk analytics work in APK.

Notes

<choreo-console-prod>/settings/onpremkeys?profile=idevp    -> to get key
auth url in config.toml -> https://analytics-event-auth.choreo.dev/auth/v1

**Comment by binodmx** [comment]
Closing the issue as analytics logs are fixed by above PRs.
