### ISSUE TITLE
Update envoy, kube

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1426]
**Description:**
update envoy version, 
java, go control plane version, 
update kube controller in adapter
update gateway spec

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Krishanx92** [comment]
Need to update common-controller version as well.
