### ISSUE TITLE
Add validation for corsConfiguration properties

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/apk#1431]
**Description:**
I am able to add unexpected properties via apk-conf file and in the response also I am seeing the unexpected field. Even though we do not want to throw a 400 when user add unexpected fields, the response should not have the unexpected field in it. 

**Suggested Labels:**
Improvement

**Steps to reproduce:**
Add cors configuration with unexpected fields and observe the response 

corsConfiguration:
  enabled: sdjsahdkjas
  accessControlAllowCredentials: true
  accessControlAllowOrigins:
  - "*"
  accessControlAllowHeaders:
  - authorization
  accessControlAllowMethods:
  - GET
  # - POST
  accessControlExposeHeaders:
  - "*"

**Comment by SanojPunchihewa** [comment]
This is fixed by https://github.com/wso2/apk/pull/1475

Now a response like below will be sent to the client

```json
{
    "code": 909029,
    "message": "Invalid apk-conf provided",
    "description": "Invalid apk-conf provided",
    "moreInfo": {
        "expected type: Boolean, found: String": "#/corsConfiguration/corsConfigurationEnabled: expected type: Boolean, found: String"
    }
}
```
