### ISSUE TITLE
Indefinite reconcile events at adapter

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/apk#1457]
**Description:**
While working on alpha testing o observed indefinite reconciliation events at the adapter side. Still could not figure out a pattern or root cause. As per @AmaliMatharaarachchi  it could be related to backend cr and something goes wrong while validating whether an event is a duplicate or not.

**Comment by AmaliMatharaarachchi** [comment]
it's related to Production Backend Properties.

**Comment by AmaliMatharaarachchi** [comment]
@Tharsanan1 did your cluster has GatewayCustomRateLimitPolicies?

**Comment by Tharsanan1** [comment]
> @Tharsanan1 did your cluster has GatewayCustomRateLimitPolicies?

Yes
