### ISSUE TITLE
Generate owner references for interceptor services and related backend crs. 

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/apk#1493]
**Description:**
$subject

**Comment by AmaliMatharaarachchi** [comment]
we decided to keep it as it is without deleting interceptor services, and related backend CRs. As these might not be defined by the API creation time. i will keep this open to make this behaviour consistant for backendjwt also. will address it with this issue.

**Comment by AmaliMatharaarachchi** [comment]
I couldn't reproduce the issue. As of now, all api related crs have owner references.(i.e. apart from jwtissuer, secrets, configsmaps, gateway, all others have owner refs). @Tharsanan1 kindly reopen this issue if you found it otherwise.
