### ISSUE TITLE
Remove URLRewrite adding to all resources 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1525]
**Description:**
we are still adding the rewrite path to each resource, it can be removed now.     

```
- path:
        type: "RegularExpression"
        value: "/post"
      method: "POST"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/post"
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tharindu1st** [comment]
This is not able to remove due to URL rewrite happening for the resource

           "regex_rewrite": {
            "pattern": {
             "regex": "^/httpbin/0.9.2/status/(.*)([/]{0,1})"
            },
            "substitution": "/status/\\1"
           }
          },
