### ISSUE TITLE
Support Prometheus 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1604]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sgayangi** [comment]
This task involves the following.
- Add Prometheus support for all APK components
- Create Grafana dashboards 
- Update documentation for APK Prometheus capabilities
- Expose Prometheus metrics for APIM APK Agent
- Update documentation for APIM APK Agent Prometheus capabilities

**Comment by sgayangi** [comment]
Relevant PRs:
APK: 
- https://github.com/wso2/apk/pull/2042
- https://github.com/wso2/apk/pull/2135

APIM APK Agent: https://github.com/wso2/product-apim-tooling/pulls?q=is%3Apr+prometheus+is%3Aclosed
Documentation: 
- APK: https://github.com/wso2/docs-apk/pull/412
- APIM APK Agent: https://github.com/wso2/docs-apk/pull/447
- https://github.com/wso2/docs-apk/pull/543
