### ISSUE TITLE
Backend Timeout Error Code Mismatch

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/apk#1627]
### Description
In [`Backend` CRD](https://github.com/wso2/apk/blob/main/helm-charts/crds/dp.wso2.com_backends.yaml#L205) under `upstreamResponseTimeout` description the response code for timeouts are defined as `408 Request Timeout`. However when a timeout occurs for an API request it gives `504 Gateway Timeout` error code.

**Comment by CrowleyRajapakse** [comment]
In envoy side there is a recent change and discussion regarding similar case like this : https://github.com/envoyproxy/envoy/issues/19725, maybe we need to update the CRD comment to include 504 as well?
