### ISSUE TITLE
Throttle out responses does not return any response

### ISSUE THREAD

**Issue by GihanAyesh** [wso2/apk#1665]
**Description:**
When trying rate-limiting with APK on terminal the implementation is working. However, no response is shown when throttled.
A normal request is shown in the first picture

![Screenshot 2023-08-24 at 12 00 58 (2)](https://github.com/wso2/apk/assets/47550159/69517322-b2d4-466f-a5f5-2ece74e69220)

The second picture shows a throttled out request. It would be better to have some kind of a respond to this.

![Screenshot 2023-08-24 at 12 00 58 (2) 2](https://github.com/wso2/apk/assets/47550159/8a068102-91b1-42ef-8293-06d9b14bd07b)

**Comment by CrowleyRajapakse** [comment]
closing due to duplicate
