### ISSUE TITLE
[Rate Limiting Feature] Not getting a Message when throttled out

### ISSUE THREAD

**Issue by Tharanidk** [wso2/apk#1669]
**Description:**
Tested the flow of API-Level rate limiting and Operation Level rate limiting features. In both of scenarios the flow worked fine. But when throttled out it doesn't give out any message to the user.

**Used CURL command:**
```
curl -k --location 'https://default.gw.wso2.com:9095/test/3.14/employee' --header 'Host: default.gw.wso2.com' --header 'Authorization: bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QiLCAia2lkIjoiZ2F0ZXdheV9jZXJ0aWZpY2F0ZV9hbGlhcyJ9.eyJpc3MiOiJodHRwczovL2lkcC5hbS53c28yLmNvbS90b2tlbiIsICJzdWIiOiI0NWYxYzVjOC1hOTJlLTExZWQtYWZhMS0wMjQyYWMxMjAwMDIiLCAiZXhwIjoxNjkyODgwNjQ2LCAibmJmIjoxNjkyODc3MDQ2LCAiaWF0IjoxNjkyODc3MDQ2LCAianRpIjoiMDFlZTQyNzItOTk0MS0xZGYwLTlkMjEtODYxNjJlZGZkMGUwIiwgImNsaWVudElkIjoiNDVmMWM1YzgtYTkyZS0xMWVkLWFmYTEtMDI0MmFjMTIwMDAyIiwgInNjb3BlIjoiZGVmYXVsdCJ9.FvKtjKiSi90fBJ973XxKSlR38CkyJ66YCApNQPfVBscaA0bCzaj7uvqPpf843TttX13lba37uKYso6nNchxiVhR75qFce7Uku-nlRLiM4tReCkm3idcE3MqTPSTNFgIsgrGQHy4eZj3gqReYV1xQY58VBR8aaleSWRZlOiUz9Qk4BDNaW4CUqF22fRpctZGH0IIUjCwCqh5IqSwGDZnqF9BmlLedT0NYSlsJShlL8GvaeJaIZVYLf6m9vC0vJpcW7-MvfboVkWVTfDH0iwetThKrOsAsSuBhDlRq7dZgPl9ohOR2kz8SefFhrRkZy_iGYFOI24xu69JvGQa90BdLHg'
```

**Test artifacts**
[artifacts.zip](https://github.com/wso2/apk/files/12429458/artifacts.zip)

**Steps to reproduce:**
1. Create and Deploy the API
2. Change the EmployeeService.apk-conf file by adding rate limiting policy.
3. Deploy the API
4. Invoke the API

**Comment by CrowleyRajapakse** [comment]
duplicate: https://github.com/wso2/apk/issues/1665

**Comment by CrowleyRajapakse** [comment]
This is expected behaviour this returns a 429 status code without any response body, will need to mention this in docs: https://github.com/wso2/docs-apk/issues/288
