### ISSUE TITLE
Kubectl get apis command response - context 

### ISSUE THREAD

**Issue by rmsamitha** [wso2/apk#1671]
**Description:**
The command “kubectl get apis -n apk” gives result with a "Context" field.
The context mentioned has “version” as a suffix. 
i.e. /test/3.14
Or is the part appended at the end can be different to the api version.

If this is exactly same as the version, isn’t it better to drop that “version” suffix from the context listed
I WSO2 APIM, we clearly distinguish these two attributes "context" and version in Publisher as below.
<img width="349" alt="image" src="https://github.com/wso2/apk/assets/2484781/51bc861a-944b-45be-9fd6-bf19e97bf8b0">

**Comment by Krishanx92** [comment]
We'll not consider this ATM, we'll re-open if needed
