### ISSUE TITLE
Ratelimit issue

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#1701]
**Description:**
1. add api ratelimits in both API level (5permin) and resource level (10permin) 
2. remove api level 
3. still resource get rate limited after only 5 requests per min

seems like ratelimit cr updates don't work

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Tharsanan1** [comment]
Could not reproduce it.
