### ISSUE TITLE
[Build/CI/CD] Bring APK repo to choreo and configure private data plane, builds etc

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/apk#179]
This task will include the following sub-tasks
1. Complete the build in the mono repo using Gradle.
2. Bring APK repo as external repo to the Choreo project
3. Provision private data plane for APK development
4. Configure deployment pipelines

**Comment by sanjeewa-malalgoda** [comment]
This task will include the following sub-tasks
1. Complete the build in the mono repo using Gradle.
2. Bring APK repo as external repo to the Choreo project
3. Provision private data plane for APK development
4. Configure deployment pipelines

**Comment by Krishanx92** [comment]
This is now move to AKS. Hense closing.
