### ISSUE TITLE
APK envoy configurations not being deleted

### ISSUE THREAD

**Issue by DDH13** [wso2/apk#2003]
**Description:**
The envoy route configurations do not get deleted when a simple REST API is undeployed. They are still visible in the config dump even afterwards. API was deployed and undeployed using CRs on the [website](https://apk.docs.wso2.com/en/latest/create-api/create-and-deploy-apis/create-api-using-cr/)

**Comment by AmaliMatharaarachchi** [comment]
This is fixed
