### ISSUE TITLE
queries on APK architecture and roadmap

### ISSUE THREAD

**Issue by stefanonegri** [wso2/apk#2004]
**Description:**
I have a few query on APK, especially because I have next week a few customer visits where I should present APK:
1) scalability: how can APK scale horizontally? I need to increase the number of replicas of envoy pods? is there anything automatic or can I control it?
2) scalability: how can I scale 'statically' deployment X APIs in one instance and Y APIs in another instance? I have to use 2 separate installations? or within the same, sharing the adapter for 2 separate envoy/enforcer pair
3) roadmap: (slide 12) what do you mean for "Gateway environment support (to support virtual environment)"
4) roadmap: (slide  12) would you mind clarifying "Semantic API versioning support for APIs"
5) in general: my understanding is that the next version will have the integration with APIM 4.3 CP, while the next a dedicated CP (initially APIs only, later with UI). Is it correct? Will next versions keep APIM CP support?

link to the roadmap I have: https://docs.google.com/presentation/d/1seMvlE3bckAkCRd6jzD2gzQgXmEgFAe7D3rddi1tcTw/edit#slide=id.g262cd9fa7fc_0_22

**Suggested Labels:**
Query

**Comment by sanjeewa-malalgoda** [comment]
#1 - please refer to - https://apk.docs.wso2.com/en/latest/setup/configure-hpa/
#2 - We have concept of API partitioning where we allocate APIs for different partition based on the partition availability. But its mostly used when there are more than 1000 APIs and creation is dynamic. If this is a dev/prod kind of envirionments or multiple departments our recommendation is to have separate deployments. If we have multiple APK installations then deploying to them also an option here.
#3 - Its a Choreo specific feature which allows to deploy APIs for multiple virtual host addresses within same API gateway runtime.
#4 - Please refer to email with heading "Semantic Versioning Based Intelligent Routing for APIs for APK"
#5 - We hope to have same control plane for both APIM and APK. So we will evolve APIM control plane to make it more cloud native and be default CP for both APIM and APK gateways.

Hope this clarifies your questions.

**Comment by stefanonegri** [comment]
perfect thank you
