### ISSUE TITLE
apim sandbox keys are not working

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#2018]
**Description:**
in enforcer logs:
```
Valid application key mapping not found in the data store for access token. Application identifier: y25WDIcPK1xL2XprOlbfJj6dPYMa, key type : PRODUCTION, security scheme : OAuth2 []
```
because the token key type was getting as production 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by CrowleyRajapakse** [comment]
This is working in the latest setup with Agent
