### ISSUE TITLE
Lack of Node Selectors, Affinity, and Anti-affinity Configurations in Helm Charts

### ISSUE THREAD

**Issue by steveliem** [wso2/apk#2022]
**Description:**
The APK documentation highlights the product's flexible deployment architecture, emphasizing features like node selectors, affinity, and anti-affinity rules for scheduling pods across various deployment environments, including multi-cluster models for high availability and disaster recovery. These features are crucial for organizations aiming to deploy APK in diverse environments, such as different data centers or cloud platforms. However, upon reviewing the Helm charts provided for APK deployment, I noticed that configurations for node selectors, affinity, and anti-affinity rules are not implemented or templated within the charts. This omission significantly reduces the deployment flexibility and the ability to optimize pod scheduling based on specific cluster architectures or requirements.

Furthermore, my experience highlights a broader issue of non-engagement from the WSO2 team with the community, both on Discord and in response to GitHub issues. This lack of interaction is concerning, especially for users seeking support and clarity on product features and configurations. I have raised concerns through the WSO2 Discord channel in the past but did not receive any response, which is disappointing. I plan to bring up this issue of community engagement, along with the specific concern regarding the Helm charts, in a discussion with Asanka at an upcoming meeting in the Netherlands at the end of March. It is crucial for the success and adoption of WSO2 products that the team responsible for community engagement actively participates in discussions, addresses user concerns, and fosters a collaborative environment.

**Suggested Labels:**
enhancement, helm, deployment, scheduling

**OS, DB, other environment details and versions:**    
- Helm version: 1.0.0 (APP version 1.16.0)

**Steps to reproduce:**
- Review the APK Helm charts for deployment configurations.
- Notice the absence of node selector, affinity, and anti-affinity rules in the Helm chart templates.

**Feature Request:**
I strongly recommend updating the Helm charts to include templates for node selectors, affinity, and anti-affinity rules. This update would ensure that the APK's deployment flexibility, as documented, can be fully realized by users, allowing for more precise pod placement strategies that cater to various operational requirements and deployment models.

**Comment by pubudu538** [comment]
Hi @steveliem,

Thank you for your valuable suggestions. Currently, our Helm chart does not support node selectors, affinity, and anti-affinity configurations. We will make sure to update the documentation accordingly. These missing features will be included in the upcoming release.

Regarding community engagement concerns, I appreciate you raising this issue. We understand the importance of community involvement. Internally, we have discussed and developed an action plan to enhance this aspect.

Thank you!
Pubudu.

**Comment by pubudu538** [comment]
This is fixed with https://github.com/wso2/apk/pull/2305. Hence closing the issue.
