### ISSUE TITLE
APK agent implementation - DP

### ISSUE THREAD

**Issue by dushaniw** [wso2/apk#21]

**Comment by AmaliMatharaarachchi** [comment]
sub tasks:

- [ ] https://github.com/wso2/apk/issues/31

**Comment by NomadXD** [comment]
## Overview

Dataplane CRs like APIs, HttpRoutes and Policies are stored in the etcd key value storage in the Kubernetes API server. The main goal of this APK Agent is to reconcile the Dataplane CRs, validate and configure the corresponding Choreo connect router instance through xDS.

## Design
![adapter-apk-agent-final drawio](https://user-images.githubusercontent.com/43727928/199022050-34174b28-89b2-46f5-a582-eb3cb4fbc8df.png)

Controller go routine contains the controllers for the CRs like API, HttpRoute, Policy and runs reconcile loops based on the state of the cache and Kubernetes API server state. 

APIController is the parent controller and watches for any changes happening to APIs and HttpRoutes.
HttpRouteController watches for HttpRoutes, Backends (Services) and Policies.
PolicyController watches for Policies.

Reconciliation sequence propagates upwards from the child controller. For example if a policy gets changed it will trigger the HttpRouteController and reconcile the related HttpRoute. This change to the HttpRoute will trigger the APIController and it will process the API reconciliation based on the data stored in the intermediate data store and Kubernetes operator cache.

APIController is the parent controller and it should be made intelligent to detect the related API events and pass the event through the channel to the synchronizer go routine.

Events passed from the APIController to the synchronizer will be of the following types.

- CREATE
API CR CREATE

- UPDATE
API CR UPDATE
HttpRoute CR CREATE
HttpRoute CR UPDATE
HttpRoute CR DELETE
Policy CR CREATE
Policy CR UPDATE
Policy CR DELETE

- DELETE
API CR DELETE    

## Intermediate storage
To save the intermediate representation we need to have thread safe hashmaps. For that we can use,
Locks / Mutex (Pessimistic concurrency control)
CAS - Compare and Swap (Optimistic concurrency control)

```go
type API struct {
	APIDefinition *v1alpha1.API
	HttpRoutes    []*gwapiv1b1.HTTPRoute
	APIPolicies   []*v1alpha1.Policy
}
```

## Channel / Buffered channel
We can use a channel or a buffered channel depending on the frequency of message passing. In this case consumer (synchronizer) may take more time to process so a buffered channel is preferred to prevent the producer (controller) getting blocked.

## Reconcile Loop
Reconcile loop breaks depending on the state of the intermediate storage and the K8s controller cache.

**Comment by AmaliMatharaarachchi** [comment]
closing as the operator has been implemented according to the above design
