### ISSUE TITLE
Add the Sample Backend to QSG instead of mocky

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/apk#2183]
**Description:**
Add the Sample Backend to QSG instead of mocky

**Comment by sgayangi** [comment]
Related docs issue: https://github.com/wso2/docs-apk/issues/474

**Comment by steveliem** [comment]
I'm using `https://httpbin.org` as a mock backend. And it works great to demo APK. 
For instance with https://httpbin.org/get you can do a GET call. It supports any possible HTTP method and technical scenario that you would like to test with.

**Comment by sgayangi** [comment]
Thanks for the recommendation! Will add it to the documentation as well.

> I'm using `https://httpbin.org` as a mock backend. And it works great to demo APK. For instance with https://httpbin.org/get you can do a GET call. It supports any possible HTTP method and technical scenario that you would like to test with.

**Comment by sgayangi** [comment]
Fixed via https://github.com/wso2/docs-apk/pull/477
https://github.com/wso2/docs-apk/pull/475
