### ISSUE TITLE
APK Quick Start Guide References Non-Working Mocky URL

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/apk#2184]
### Issue Description
In the APK Quick Start Guide (QSG), there is a reference to an Open API file hosted at `https://run.mocky.io/v3/1327c339-354b-4080-8296-f6268365e67b`. It appears that this URL is no longer functioning correctly as attempts to access it result in an error or no response.

### Steps to Reproduce
1. Navigate to the section in the APK Quick Start Guide where the Open API file is referenced.
2. Try to access the URL: https://run.mocky.io/v3/1327c339-354b-4080-8296-f6268365e67b in sample API config.
3. Observe the failure in accessing the resource.

### Possible Solutions
- Verify if the URL is correct and if the resource is still hosted at that location.
- If the resource has been moved, update the Quick Start Guide with the new URL.
- Alternatively, consider hosting the simple reliable service in Choreo
- Or we can recommend to use HTTPBin service which is light weight and easy to install in k8s

### Additional Context
This issue is critical for new users who are following the Quick Start Guide to learn and implement APK. Ensuring that all resources are accessible and up-to-date is essential for providing a smooth onboarding experience.

**Comment by sgayangi** [comment]
Updated via PR https://github.com/wso2/docs-apk/pull/475
Updated documentation link - https://apk.docs.wso2.com/en/1.1.0/get-started/quick-start-guide/#step-3-create-the-backend

- Provides a custom Kubernetes service to serve as a backend for the EmployeeService API.
