### ISSUE TITLE
APK Quick Start Guide Lacks Instructions for Existing APK Deployments

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/apk#2185]
### Issue Description
The current APK Quick Start Guide (QSG) does not provide instructions or guidance for users who already have an existing APK deployment in their Kubernetes cluster. Users who wish to start fresh with the steps provided in the QSG may encounter conflicts or issues due to pre-existing APK configurations, CRDs (Custom Resource Definitions), or other related resources.

### Steps to Identify the Issue
1. User has an existing APK deployment in their Kubernetes cluster.
2. User follows the APK Quick Start Guide without clearing the existing APK deployment or related resources.
3. Potential conflicts or issues arise due to overlapping or pre-existing resources.

### Expected Behavior
The Quick Start Guide should provide a clear set of instructions or a warning for users who already have an APK deployment. It should guide them on how to properly clear their existing deployment or how to safely integrate or update their current setup with the new instructions.

### Suggested Improvements
1. **Add a Pre-check Section:** Introduce a pre-check section in the QSG that guides users on how to check for existing APK deployments and related resources.
   
2. **Provide Clear Instructions:** Offer clear instructions on how to remove or update existing APK deployments. This could include kubectl commands to delete specific APK-related CRDs or resources, or guidance on updating and integrating with the new setup.

3. **Cluster Restart Warning:** If a cluster restart is a recommended step, provide explicit instructions and warnings about the implications and the exact steps to perform a safe restart.

4. **Backup Reminder:** Advise users to back up any important data or configurations before making significant changes to their APK deployment or Kubernetes cluster.

**Comment by sgayangi** [comment]
Update as of 18/04/2024:
- Instructions to uninstall the APK have been added under the [Uninstall APK](https://apk.docs.wso2.com/en/latest/setup/uninstall/) section in the documentation
- The section has been linked in all 3 QSGs
- Pre check section is in progress
