### ISSUE TITLE
Control plane default settings are missing in the open source helm chart

### ISSUE THREAD

**Issue by metcox** [wso2/apk#2203]
**Description:**

Control plane default settings are missing in the open source helm chart

**Suggested Labels:**

apk-1.1.0, component/helm

**Suggested Assignees:**

**Affected Product Version:**

1.1.0-alpha2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

    helm repo add wso2apk https://github.com/wso2/apk/releases/download/1.1.0-alpha2
    helm install apk wso2apk/apk-helm --version 1.1.0-alpha2

produces a lot of "Error: template: ***** at <.Values.wso2.apk.cp.enabled>: nil pointer evaluating interface {}.enabled"
for instance:

    Error: template: apk-helm/templates/data-plane/gateway-components/gateway-runtime/gateway-runtime-deployment.yaml:35:28: executing "apk-helm/templates/data-plane/gateway-components/gateway-runtime/gateway-runtime-deployment.yaml" at <include (print $.Template.BasePath "/data-plane/gateway-components/log-conf.yaml") .>: error calling include: template: apk-helm/templates/data-plane/gateway-components/log-conf.yaml:1:45: executing "apk-helm/templates/data-plane/gateway-components/log-conf.yaml" at <.Values.wso2.apk.cp.enabled>: nil pointer evaluating interface {}.enabled

**Related Issues:**

**Comment by sgayangi** [comment]
Hi, thank you for creating an issue!
Could you check your helm version, and ensure that it is in the prerequisites as mentioned in https://apk.docs.wso2.com/en/latest/setup/prerequisites/#package-manager-requirement ?

**Comment by pubudu538** [comment]
Hi @metcox ,

You can get this issue if you are using a new values.yaml and disable the wso2.apk.dp. If that is the case, to overcome, please add the following value to disable the cp in the values.yaml

```
wso2:
  apk:
    cp:
      enabled: false
```

Please share your installation steps otherwise. We would like to improve the product. 

Thank you!
Pubudu.

**Comment by metcox** [comment]
I had 2 versions of HELM installed, I was using the wrong one (outdated), installation is good now, sorry for the inconvenience.
