### ISSUE TITLE
second helm installation of apk fails

### ISSUE THREAD

**Issue by DDH13** [wso2/apk#2222]
**Description:**
After installing and uninstalling the apk once, a second installation attempt would fail. However, resetting the cluster solves the problem
![image](https://github.com/wso2/apk/assets/63235220/1184157e-c748-40a5-ad4d-3d2a3012797c)

**Comment by pubudu538** [comment]
Incase of a failure due to common controller unavailability, users can upgrade the installation as follows.

helm upgrade apk wso2apk/apk-helm --version 1.1.0-alpha2 --set wso2.apk.webhooks.conversionwebhookconfigurations=false
