### ISSUE TITLE
Requests sent to a rate limited API are not throttled upon exceeding API rate limit

### ISSUE THREAD

**Issue by sgayangi** [wso2/apk#2226]
**Description:**
1. Create an API with a RateLimitPolicy
2. Invoke the API until the limit is exceeded
3. Use the following command and note that the relevant CR has been updated.
```
kubectl get ratelimitpolicies -n apk
```
4. Even after the limit is exceeded, the API can be called without an issue when it should get a 429 response.

However, when the common controller pod is restarted, it works as expected.

**Comment by sgayangi** [comment]
The issue has been reproduced in the beta pack as well, therefore needs to be fixed.

**Comment by Tharsanan1** [comment]
Fixed intermittent ratelimit issues with: https://github.com/wso2/apk/pull/2446
