### ISSUE TITLE
Rate limit CRs are not updated when the ratelimit is updated from the APIM

### ISSUE THREAD

**Issue by sgayangi** [wso2/apk#2227]
**Description:**
1. Create an API level rate limit
2. Save and deploy the API
3. Then update the ratelimit by changing the selected rate limit
4. Save and deploy the API
5. Check the rate limit CR - it has not been updated.

This was observed for GraphQL APIs and resource level rate limit policies for REST APIs as well.

**Comment by CrowleyRajapakse** [comment]
this works in beta, let's verify

**Comment by sgayangi** [comment]
Issue not reproduced in beta pack, therefore closing this issue
