### ISSUE TITLE
Authentication CR is always created with mTLS mandatory

### ISSUE THREAD

**Issue by sgayangi** [wso2/apk#2246]
**Description:**
1. Deploy an API on APIM
2. Enable mTLS and make it optional
3. Save and deploy the API
4. View the Authentication CR - it has been created with mTLS mandatory

This happens for both GraphQL and REST APIs

**Comment by CrowleyRajapakse** [comment]
This works in beta, shall we verify

**Comment by sgayangi** [comment]
Issue not reproduced in latest beta pack, therefore closing this issue.
