### ISSUE TITLE
[DP to CP] adding api key crashed adapter

### ISSUE THREAD

**Issue by DDH13** [wso2/apk#2312]
**Description:**

Applying the below CR for authorization using api key caused a panic

Adapter logs:
![image](https://github.com/wso2/apk/assets/63235220/3e5b05da-20b7-4f0e-b430-216f342d03f5)

Authentication CR:
apiVersion: "dp.wso2.com/v1alpha2"
kind: "Authentication"
metadata:
  name: employee-auth-apikey
  namespace: apk
spec:
  override: 
    authTypes:
      apiKey:
      - in: Header
        name: x-api-key
  targetRef:
    group: "gateway.networking.k8s.io"
    kind: API
    name: empapi

**Comment by Tharsanan1** [comment]
Fixed with: https://github.com/wso2/apk/pull/2313
