### ISSUE TITLE
Issue with status in API CRs

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#2348]
**Description:**
The current status object is incrementally adding entries to the api.spec.status without any limits. This would cause unnecessary lengthy crs and can attribute to exceeded memory limits. So, a proper condition management should be added as describe in gateway spec.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Tharsanan1** [comment]
Fixed the indefinitely growing status.events by capped the size with max 7 events. https://github.com/wso2/apk/pull/2553

**Comment by Tharsanan1** [comment]
We need to improve the API CRD to support Gateway spec like statuses. I have created this improvement issue for this: https://github.com/wso2/apk/issues/2554
