### ISSUE TITLE
API deployment not working (APIM 4.3.0 as control plan)

### ISSUE THREAD

**Issue by dushansachinda** [wso2/apk#2375]
Testing with Rancher 1.11.0

Following document https://apk.docs.wso2.com/en/latest/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg/

- APIM and APK and APK agents up and running
-  When deploy API I can see agent prints the logs as 
024-05-15 22:57:38 INFO [health.go:50] - [health.service.SetStatus] [-] Update health status of service "apk.apim.agent.internal.CommonControllerGrpcService" as HEALTHY []
[GIN] 2024/05/15 - 22:57:43 | 200 |     217.833µs |     10.42.0.164 | GET      "/subscriptions"
[GIN] 2024/05/15 - 22:57:43 | 200 |     157.958µs |     10.42.0.164 | GET      "/applications"
[GIN] 2024/05/15 - 22:57:43 | 200 |          52µs |     10.42.0.164 | GET      "/applicationmappings"
2024-05-15 22:59:29 INFO [notification_listener.go:87] - [messaging.handleNotification] [-] Event API_CREATE is received []
2024-05-15 22:59:34 INFO [notification_listener.go:87] - [messaging.handleNotification] [-] Event DEPLOY_API_IN_GATEWAY is received []
2024-05-15 23:00:13 INFO [notification_listener.go:87] - [messaging.handleNotification] [-] Event API_LIFECYCLE_CHANGE is received []
2024-05-15 23:03:33 INFO [notification_listener.go:87] - [messaging.handleNotification] [-] Event DEPLOY_API_IN_GATEWAY is received []
2024-05-15 23:03:33 INFO [notification_listener.go:87] - [messaging.handleNotification] [-] Event REMOVE_API_FROM_GATEWAY is received []

However, not finding API deployed at APK DP

dushan:APK dushan$ kubectl get apis -n apk
NAME                                          API NAME                                VERSION   BASEPATH                        ORGANIZATION   AGE
apk-wso2-apk-dcr-api                          dcr-api                                 1.0.0     /dcr/1.0.0                      apk-system     54m
apk-wso2-apk-jwks-endpoint-ds-api             jwks-domain-service                     1.0.0     /.wellknown/jwks/1.0.0          apk-system     54m
apk-wso2-apk-oauth-api                        oauth-api                               1.0.0     /oauth2/1.0.0                   apk-system     54m
apk-wso2-apk-wso2-apk-config-deployer-api     WSO2 APK Config Deployer API            1.1.0     /api/deployer/1.1.0             apk-system     54m
apk-wso2-apk-wso2-apk-config-generator-api    WSO2 APK Config Generator API           1.1.0     /api/configurator/1.1.0         apk-system     54m
apk-wso2-apk-wso2-apk-notification-api        WSO2 APK Notification API               1.0.0     /api/notification/1.0.0         apk-system     54m
apk-wso2-apk-authentication-endpoint-ds-api   authenticationEndpoint-domain-service   1.0.0     /authenticationEndpoint/1.0.0   apk-system     54m
apk-wso2-apk-commonoauth-api                  commonoauth-api

default namespace not showing anything

**Comment by CrowleyRajapakse** [comment]
Hi,
Can you attach full agent logs?

**Comment by CrowleyRajapakse** [comment]
This issue got resolved, it was due to the conflict of running DP to CP instead of CP to DP agent.
