### ISSUE TITLE
GRPC support

### ISSUE THREAD

**Issue by Krishanx92** [wso2/apk#2416]
Tasks
- Introduce new API type v1alpha3
- Update the .proto parser
- Test scenarios for all types of gRPC communications
- Analytics support for gRPC APIs

**Comment by sgayangi** [comment]
- [ ] Update the proto parser
- [ ] Test scenarios for all types of gRPC communications

**Comment by sgayangi** [comment]
### Update - 27th August 2024

- Implementation changes from PR https://github.com/wso2/apk/pull/2369/files have been added
- Parser updated for single .proto files

To be completed:
- Add support for multiple .proto files provided as a .zip file
- Add authentication support (OAuth2, mTLS and APIKey)
- Add analytics support
- Look into providing seperate dashboard for gRPC APIs

**Comment by sgayangi** [comment]
### Update - 3rd Septermber 2024

- Research was done for parser support for .proto files
- .proto files do not have a Java native parser to parse the .proto files
- Recommended approach is to compile the .proto files into a .desc file using the [protoc compiler](https://grpc.io/docs/protoc-installation/)
- The protoc compiler does not have native support in Java and therefore the files need to be provided as descriptor files or the files need to be compiled during runtime as part of a Java background process
- As of now, proceeding with assuming the .desc files are provided as input for the config generator call

**Comment by sgayangi** [comment]
### Update - 5th Sepember 2024

- After discussion with the APK team, it was decided that complete parsing and validation of .proto files were not necessary
- Since only the service names across all files are necessary for the creation of all relevant GRPCRoutes, the .proto files are parsed to obtain the service names
