### ISSUE TITLE
Need to add AI RateLimit Configuration to Import API Flow in DP to CP

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/apk#2494]

**Comment by Tharsanan1** [comment]
Feature added: https://github.com/wso2/apk/pull/2490, https://github.com/wso2/apk/pull/2498

**Comment by Tharsanan1** [comment]
Feature added: https://github.com/wso2/apk/pull/2490, https://github.com/wso2/apk/pull/2498
