### ISSUE TITLE
[APK Management server and Adapter] Extract Data for Enforcer XDS

### ISSUE THREAD

**Issue by npamudika** [wso2/apk#32]
**Description:**
This is to extract data for Enforcer XDS.

Need to debug and check how enforcer gets consumer keys currently (it's not via xDS currently).
Update application.proto to send consumer keys and do the related changes in enforcer side.

- [ ] ApplicationData CRD (which contains a list of apps) has changed to single Application CRD. Need to consider this design change.

**Comment by Amila-Rukshan** [comment]
Changes are in this PR for now https://github.com/wso2/product-microgateway/pull/3128 and will be moved to apk repo

**Comment by Amila-Rukshan** [comment]
https://github.com/wso2/apk/pull/116 merged
