### ISSUE TITLE
[APK Management server and Adapter] Management Server to DB Data Transfer

### ISSUE THREAD

**Issue by npamudika** [wso2/apk#33]
**Description:**
This is to track the PostgreSQL transactions related to Management Server.

**Comment by npamudika** [comment]
PostgreSQL DB Schema Document - https://docs.google.com/document/d/1fqM2qKeDVfAHwvyn6AtWazFdVji2pwadWFNOEmX0LR8/edit?usp=sharing

**Comment by npamudika** [comment]
DB Schema Related Changes - https://docs.google.com/spreadsheets/d/1cbLbByhjI9utt4WzcqED4J8BOx3uVG_44wpMZmeKKHc/edit?usp=sharing

This sheet contains the list of tables with the fields and applicability of each domain service (Admin, Runtime, DevPortal and BackOffice)

**Comment by npamudika** [comment]
@AmaliMatharaarachchi will follow up on this task.

**Comment by AmaliMatharaarachchi** [comment]
closing as this is completed
