### ISSUE TITLE
Design operator controller watch model for CRDs

### ISSUE THREAD

**Issue by Amila-Rukshan** [wso2/apk#343]
**Description:**
Findings - https://docs.google.com/document/d/1WnRl7t6OmSVK4Fj71vYtexyFEGfR357Csy6hca9wVSg/edit#

**Comment by AmaliMatharaarachchi** [comment]
This can be closed as the controller model is finalized as mentioned in this doc. https://docs.google.com/document/d/18KdzWaqI5RJy3s-aBq7tXlgFUfz3DMZRgPhHuf65lns/edit#
