### ISSUE TITLE
Integration tests for operator

### ISSUE THREAD

**Issue by Amila-Rukshan** [wso2/apk#557]
**Description:**

Should test API deployment with different configuration resources and invocation.

Check the ability to run conformance tests as a part of this
https://gateway-api.sigs.k8s.io/concepts/conformance/?h=conforma#running-tests

**Comment by Amila-Rukshan** [comment]
PRs for this task:

- https://github.com/wso2/apk/pull/716
- https://github.com/wso2/apk/pull/720
- https://github.com/wso2/apk/pull/749
- https://github.com/wso2/apk/pull/780

**Comment by Krishanx92** [comment]
- [ ] [tests] request and response header modify
