### ISSUE TITLE
same API can be deployed in multiple namespaces

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#560]
**Description:**
Validations should be added to restrict by API context. APIs with same API contexts should not be able to deploy.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Amila-Rukshan** [comment]
Fixed by https://github.com/wso2/apk/pull/561
