### ISSUE TITLE
[Runtime DS] Need to design adding vHost capability when creating API through Runtime API.

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/apk#616]
**Description:**
Need to design adding vHost capability when creating API through Runtime API. Currently users have no option to select or define the vHost entries related to endpoints in the payload. Hence, when invoking the API created through Runtime /apis POST request, needs to be access through default vHost(gw.wso2.com).

**Comment by tharindu1st** [comment]
This is done through apk-conf
