### ISSUE TITLE
[Helm] Disable Postgres DB flag doesn't work 

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/apk#677]
**Description:**
When setting only DP components, we are setting flags as --set wso2.apk.cp.enabled=false --set wso2.apk.cp.postgresql.enabled=false, but the DB pod is getting spin up.

**Comment by CrowleyRajapakse** [comment]
admin@sampath ~ % kubectl get pods -n apk
NAME                                                           READY   STATUS    RESTARTS      AGE
apk-test-cert-manager-5489f4cc85-l9r8d                         1/1     Running   0             2m28s
apk-test-cert-manager-cainjector-778cf8949d-p598x              1/1     Running   0             2m28s
apk-test-cert-manager-webhook-cbf84648b-8q6mh                  1/1     Running   0             2m28s
apk-test-wso2-apk-adapter-deployment-7564c57f66-vtm7f          1/1     Running   4 (53s ago)   2m28s
apk-test-wso2-apk-gateway-runtime-deployment-f759fdbb4-9j8qs   2/2     Running   0             2m28s
apk-test-wso2-apk-idpds-deployment-5495544b9c-zwt8k            1/1     Running   0             2m28s
apk-test-wso2-apk-idpui-deployment-74f45c8cc6-4cqmg            1/1     Running   0             2m28s
apk-test-wso2-apk-runtime-ds-deployment-589c4d4d54-ltwlb       1/1     Running   0             2m28s
wso2apk-db-service-0                                           1/1     Running   0             2m28s
admin@sampath ~ %

**Comment by tharindu1st** [comment]
to remove database from deployment need to comment **postgresql:** section in values.yaml
