### ISSUE TITLE
Add backend JWT to CRD

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#782]
**Description:**
currently backend jwt is only configurable at gateway level. Discuss whether this needs to be added to the backend policy CR's security section.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by BLasan** [comment]
Issue is fixed via https://github.com/wso2/apk/pull/1153
