### ISSUE TITLE
[APK Management Server to Agent Client Communication] Implement agent to management server GRPC unary call 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#83]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Tharsanan1** [comment]
Fixed with: https://github.com/wso2/apk/pull/101
