### ISSUE TITLE
[APK Management Server and Adapter] initiate and configure the Database connection

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#84]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by VajiraPrabuddhaka** [comment]
closing this as a duplicate of https://github.com/wso2/apk/issues/120
