### ISSUE TITLE
[APK Agent Implementation] APK Agent gateway operator basic functionality with API and HttpRoute CRDs

### ISSUE THREAD

**Issue by NomadXD** [wso2/apk#98]
**Description:**
Dataplane CRs like APIs and HttpRoutes are stored in the etcd key value storage in the Kubernetes API server. The main goal of this task is to reconcile the Dataplane CRs, validate and configure the corresponding gateway router instance through xDS.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by AmaliMatharaarachchi** [comment]
closing as this is fixed
