### ISSUE TITLE
Portal application development

### ISSUE THREAD

**Issue by chanaka3d** [wso2/apk#980]
**Description:**
This task focuses on developing three web applications: admin, backoffice, and runtime. 

The following has to be done in the three applications. Initially in the admin app.

Admin portal authentication

- [ ]  Make Authentication configurable ( enable PKCE, switch IDP from internal to Asgardio/Oath0/Okta, etc.. )
- [ ] Token storing as an HTTP-only cookie now. We need to make it more secure with a token split or something.
- [ ] Bring the sensitive info in the setting.js into env variables.
- [ ] Make the build break if the generated types do not match the UI implementation.

Admin portal UIs

- [ ] Application Rate Plan
- [ ] Deny policy
- [ ] Organization
- [ ] Business plan
- [ ] Key manager
- [ ] Advanced policy
- [ ] Import export throttling policy
- [ ] Applications
- [ ] Environments
- [ ] Bot detection
- [ ] Monetization
- [ ] Workflow
- [ ] API Categories
- [ ] Admin Settings
- [ ] System scopes
- [ ] Role existence check
- [ ] Tenant theme
- [ ] Tenant config

**Comment by chanaka3d** [comment]
This PR is updating the Types to latest and updating the readme file with informative description about the UI development and it's architectre.

**Comment by Krishanx92** [comment]
Currently on hold, hence closing. will reopen if needed.
